name: Python script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install discord.py
          pip install yt-dlp

      - name: Run a Python script
        env:
          DISCORD_SECRET_TOKEN: ${{ secrets.DISCORD_SECRET_TOKEN2 }}
        run: python .github/workflows/musicbot.py
